### ISSUE TITLE
  disableDebugPorts();

### ISSUE THREAD

**Issue by ghost** [rbarreiros/FV1-Touch#2]
disableDebugPorts();
is needed to be able to use PB3 & PB4 pins as GPIO pins

**Comment by rbarreiros** [comment]
Didn't notice on the schematic they were being used, as its stated in the start of the file, I used another stm32 to Arduino port (a more standard one) that doesn't have that function, shouldn't be hard to port (I would guess all you need is to pinmode those ports)

**Comment by rbarreiros** [comment]
After further reading (have no idea how Dan drown stm32 port works) if you use the port I was using, you don't need to call disabledebugports, just set the ports as outputs or inputs.
